events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream book-service {
        server book-service:8002;
    }

    upstream loan-service {
        server loan-service:8003;
    }

    upstream user-service {
        server user-service:8004;
    }

    server {
        listen 80;

        location /api/books {
            proxy_pass http://book-service;
        }

        location /api/loans {
            proxy_pass http://loan-service;
        }

        location /api/users {
            proxy_pass http://user-service;
        }
    }
}